# SimonPlugin Configurations
# For all format configuration, use {0} as username and {1} as the content.

# For Greylisting and Reports
sql:
  hostname: localhost
  username: username
  password: password
  database: minecraft

report:
  prefix: "&d[Report]"
